# Интервал проверки в тиках (20 тиков = 1 секунда)
check-interval-ticks: 600

# Максимальный уровень заражения
max-infection-level: 100

# Нижний порог Y для заражения
y-threshold-low: 16

# Верхний порог Y для снижения заражения
y-threshold-high: 20

# Шанс снижения заражения при сне на кровати (в процентах)
bed-sleep-reduce-chance: 20

# Шанс получить слепоту при заражении >= 3 (в процентах)
blindness-chance: 10

# Шанс получить замедление при заражении >= 10 (в процентах)
slowness-chance: 10

# Шанс поджечь при заражении > 30 и у бедрока (в процентах)
fire-chance: 3

# Шанс получить иссушение при заражении > 35 в темноте (в процентах)
wither-chance: 15
