name: lore
version: 1.0
main: com.blussful.lore.Lore
api-version: 1.21
authors:
  - blussful
  - txonikla
commands:
  lr:
    description: Команды плагина Lore (заражение)
    usage: /<command> <stats|set|reload> [ник] [уровень]
    permission: lore.admin
    permission-message: "§cУ вас нет прав на использование этой команды."
